version: 2
jobs:
  build:
    machine:
      image: circleci/classic:201708-01
      
    steps:
    - checkout
    - run:
        name: Install dependencies
        command: |
          sudo apt-get update
          sudo apt-get install python-pip
          sudo pip install ecs-deploy
        
    - run:
        name: Build Container and send to ECR
        command: |
          $(aws ecr get-login --no-include-email --region us-east-1)
          docker build -t $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/golang-webserver:$CIRCLE_SHA1 .
          docker push $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/$REPONAME:$CIRCLE_SHA1
          

    - run:
        name: Run container and curl it
        command: |
          docker run -d -p 8080:8000 --name sample-go-webapp $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/golang-webserver:$CIRCLE_SHA1; sleep 10
          curl --retry 10 --retry-delay 5 localhost:8080

    - deploy:
        command: ecs deploy $CLUSTER $SERVICE --timeout 600 --region us-east-1 --image golang $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/golang-webserver:$CIRCLE_SHA1
          


        #machine:
        #  services:
        #- docker

        #dependencies:
        # post:
        #    - docker build -t $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/golang-webserver:$CIRCLE_SHA1 .

        #test:
        #  post:
        #  - docker run -d -p 8080:8000 --name sample-go-webapp $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/golang-webserver:$CIRCLE_SHA1; sleep 10
        #  - curl --retry 10 --retry-delay 5 localhost:8080

        #deployment:
        #  prod:
        #    branch: master
        #    commands:
        #      - ./deploy.sh dev
